

@baseUrl = http://localhost:8000/my_app
@taskId = 14
### Get all tasks
GET {{baseUrl}}/books HTTP/1.1

### Get all tasks
GET {{baseUrl}}/authors HTTP/1.1
### Get all tasks
GET {{baseUrl}}/publishers HTTP/1.1
### Get all tasks
GET {{baseUrl}}/categories HTTP/1.1



### Get all tasks
POST {{baseUrl}}/author/add/ HTTP/1.1
Content-Type: application/json

{
    "firstname": "Yukino",
    "lastname": "Yukinoshita",
    "email": "123@gmail.com"
}


###
GET {{baseUrl}}/publishers/ HTTP/1.1

###
POST {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "user1",
    "password": "123456aA@"
}



curl -X GET http://127.0.0.1:8000/myapp/books/


curl -X GET http://127.0.0.1:8000/myapp/publishers/ \
    -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3OTczMzk1LCJpYXQiOjE3NDc5Njk3OTUsImp0aSI6IjMxMjU3YzBmYWY0NzQyMWE4OWJjMjQ3YTM3MjU2NmQzIiwidXNlcl9pZCI6MX0.VEtA9Zf8jEjVgsUnCx_19pcDIrqvgPs6WZeSvfCVTMc"

###

POST {{baseUrl}}/login/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "akerman0509",
    "password": "1111"
}
